# Generated by Django 2.0.4 on 2018-04-05 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField()),
                ('response_code', models.CharField(blank=True, max_length=3, null=True)),
                ('response_source', models.CharField(blank=True, max_length=20, null=True)),
                ('response_text', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=32)),
                ('operation', models.CharField(choices=[('AUTH', 'AUTH'), ('SALE', 'SALE'), ('CAPTURE', 'CAPTURE'), ('CREDIT', 'CREDIT'), ('ANNUL', 'ANNUL')], max_length=7)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField()),
                ('response_code', models.CharField(blank=True, max_length=3, null=True)),
                ('response_source', models.CharField(blank=True, max_length=20, null=True)),
                ('response_text', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('order_number', models.CharField(max_length=32)),
                ('amount', models.PositiveIntegerField()),
                ('currency_code', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='netaxept.Payment'),
        ),
    ]
