# Generated by Django 2.0.4 on 2018-07-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netaxept', '0002_auto_20180408_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='auto_auth',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='redirect_url',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
